const mongoose = require('mongoose');

const productSchema = new mongoose.Schema({
  id: { type: String }, // Optional, since it could be auto-generated by MongoDB
  name: { type: String, required: true },
  price: { type: Number, required: true },
  image: { type: String }, // Optional field
  description: { type: String, required: true },
  discountAmount: { type: Number }, // Optional field
  categoryId: { type: String, required: true },
  stock: { type: Number, required: true },
  created: { type: Number }, // Optional, could store timestamps
  modified: { type: Number } // Optional, could store timestamps
});

module.exports = mongoose.model('Product', productSchema);
